#!/usr/bin/env python3
"""
astro_chart.py
Real (computed, not invented) Vedic/sidereal astrology chart for a moment in
time and place — ascendant, moon sign/nakshatra, 7th house, day lord, hora
lord, and the positions of Mars/Saturn/Jupiter/Rahu/Ketu. Built for the
sports-astrology "muhurta" (electional) prediction feature: the match's
start-time + venue stand in for a birth chart's time + place.

Uses the Swiss Ephemeris (pyswisseph) with the Lahiri ayanamsa — the standard
reference point for Vedic astrology. This module does real astronomical
computation; nothing here is generated by an LLM. Claude is only handed the
OUTPUT of compute_chart() to narrate, so the astrology "facts" a video states
(e.g. "Moon in Scorpio") are always astronomically real for that match's
exact start time and venue, even though the entertainment-astrology
INTERPRETATION built on top of them is not a scientific claim.

Simplifications made deliberately, for entertainment content rather than a
professional Jyotish practice, and documented rather than hidden:
- Hora (planetary hour) division uses 24 EQUAL hours from sunrise to the next
  sunrise, not the classical unequal day-hours/night-hours split. This is a
  common software simplification; it can shift the hora lord near dawn/dusk
  on some dates.
- Venue coordinates come from a small curated city/country lookup
  (VENUE_COORDS below), not stadium-precise geocoding — fine for sign-level
  astrology (which changes over hours/days), immaterial for house-level
  precision at the degree of confidence this content claims.
"""
from datetime import datetime, timedelta, timezone

import swisseph as swe

swe.set_sid_mode(swe.SIDM_LAHIRI)

SIGNS = [
    "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
    "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces",
]

NAKSHATRAS = [
    "Ashwini", "Bharani", "Krittika", "Rohini", "Mrigashira", "Ardra",
    "Punarvasu", "Pushya", "Ashlesha", "Magha", "Purva Phalguni", "Uttara Phalguni",
    "Hasta", "Chitra", "Swati", "Vishakha", "Anuradha", "Jyeshtha",
    "Mula", "Purva Ashadha", "Uttara Ashadha", "Shravana", "Dhanishta",
    "Shatabhisha", "Purva Bhadrapada", "Uttara Bhadrapada", "Revati",
]

# Weekday ruler (Python weekday(): Monday=0 .. Sunday=6).
WEEKDAY_LORD = {
    0: "Moon", 1: "Mars", 2: "Mercury", 3: "Jupiter",
    4: "Venus", 5: "Saturn", 6: "Sun",
}

# Chaldean order, used both for the hora-lord cycle and as a rough classical
# "strength/speed" ranking — slowest-moving (traditionally most tortuous)
# first. Only used internally for the hora cycle here.
CHALDEAN = ["Saturn", "Jupiter", "Mars", "Sun", "Venus", "Mercury", "Moon"]

# Classical dignity table: (exaltation sign, own sign(s), debilitation sign).
# Standard Vedic doctrine — public-domain astrological reference data, not
# something that needs a live source.
DIGNITY = {
    "Sun":     {"exalt": "Aries",   "own": {"Leo"},               "debil": "Libra"},
    "Moon":    {"exalt": "Taurus",  "own": {"Cancer"},             "debil": "Scorpio"},
    "Mars":    {"exalt": "Capricorn", "own": {"Aries", "Scorpio"}, "debil": "Cancer"},
    "Mercury": {"exalt": "Virgo",   "own": {"Gemini", "Virgo"},    "debil": "Pisces"},
    "Jupiter": {"exalt": "Cancer",  "own": {"Sagittarius", "Pisces"}, "debil": "Capricorn"},
    "Venus":   {"exalt": "Pisces",  "own": {"Taurus", "Libra"},    "debil": "Virgo"},
    "Saturn":  {"exalt": "Libra",   "own": {"Capricorn", "Aquarius"}, "debil": "Aries"},
    "Rahu":    {"exalt": "Taurus",  "own": set(),                  "debil": "Scorpio"},
    "Ketu":    {"exalt": "Scorpio", "own": set(),                  "debil": "Taurus"},
}

_PLANET_ID = {
    "Sun": swe.SUN, "Moon": swe.MOON, "Mars": swe.MARS, "Mercury": swe.MERCURY,
    "Jupiter": swe.JUPITER, "Venus": swe.VENUS, "Saturn": swe.SATURN,
    "Rahu": swe.MEAN_NODE,   # mean lunar node; Ketu is always 180° opposite
}

# A small curated lookup — good enough for sign-level astrology, not
# stadium-precise geocoding. Extend as new venues come up; unknown venues
# fall back to the country entry, then to a documented neutral default.
VENUE_COORDS = {
    # country-level centroids / capital-ish coordinates
    "england": (51.5, -0.12), "united kingdom": (51.5, -0.12), "uk": (51.5, -0.12),
    "india": (28.6, 77.2), "australia": (-33.9, 151.2), "usa": (38.9, -77.0),
    "united states": (38.9, -77.0), "brazil": (-15.8, -47.9), "argentina": (-34.6, -58.4),
    "germany": (52.5, 13.4), "france": (48.9, 2.4), "spain": (40.4, -3.7),
    "italy": (41.9, 12.5), "portugal": (38.7, -9.1), "netherlands": (52.4, 4.9),
    "pakistan": (33.7, 73.1), "sri lanka": (6.9, 79.9), "bangladesh": (23.8, 90.4),
    "new zealand": (-41.3, 174.8), "south africa": (-25.7, 28.2), "west indies": (18.0, -76.8),
    "jamaica": (18.0, -76.8), "ireland": (53.3, -6.3), "scotland": (55.9, -3.2),
    "wales": (51.5, -3.2), "japan": (35.7, 139.7), "china": (39.9, 116.4),
    "uae": (25.2, 55.3), "united arab emirates": (25.2, 55.3), "qatar": (25.3, 51.5),
    "saudi arabia": (24.7, 46.7), "mexico": (19.4, -99.1), "canada": (45.4, -75.7),
}
_DEFAULT_COORDS = (51.5, -0.12)   # London — documented neutral fallback


def venue_coords(venue: str, country: str) -> tuple:
    """Best-effort (lat, lon) for a venue/country string. Not stadium-precise
    geocoding — see module docstring."""
    key = (country or "").strip().lower()
    if key in VENUE_COORDS:
        return VENUE_COORDS[key]
    combined = f"{venue} {country}".lower()
    for name, coords in VENUE_COORDS.items():
        if name in combined:
            return coords
    return _DEFAULT_COORDS


def _sign_of(longitude: float) -> str:
    return SIGNS[int(longitude // 30) % 12]


def _nakshatra_of(longitude: float) -> str:
    return NAKSHATRAS[int(longitude // (360 / 27)) % 27]


def _dignity_label(planet: str, sign: str) -> str:
    d = DIGNITY.get(planet)
    if not d:
        return "neutral"
    if sign == d["exalt"]:
        return "exalted"
    if sign == d["debil"]:
        return "debilitated"
    if sign in d["own"]:
        return "in own sign"
    return "neutral"


def _sidereal_longitude(jd: float, planet_id: int) -> float:
    res, _flag = swe.calc_ut(jd, planet_id, swe.FLG_SIDEREAL)
    return res[0] % 360


def _sunrise_window(jd_local_midnight: float, lat: float, lon: float) -> tuple:
    """(sunrise_jd, next_sunrise_jd) bracketing jd_local_midnight's solar day,
    used for the hora (planetary hour) division below."""
    geopos = (lon, lat, 0)
    _res, tret = swe.rise_trans(jd_local_midnight, swe.SUN, rsmi=swe.CALC_RISE, geopos=geopos)
    sunrise = tret[0]
    _res, tret2 = swe.rise_trans(sunrise + 0.5, swe.SUN, rsmi=swe.CALC_RISE, geopos=geopos)
    next_sunrise = tret2[0]
    return sunrise, next_sunrise


def _day_and_hora_lord(dt_utc: datetime, lat: float, lon: float) -> tuple:
    """Vedic day boundary is sunrise-to-sunrise, not midnight-to-midnight —
    a match at 2 AM still belongs to the PREVIOUS day's weekday lord. Hora
    (planetary hour) lord cycles through CHALDEAN order starting from the
    day lord at sunrise; see the equal-hour simplification note in the
    module docstring."""
    jd_now = swe.julday(dt_utc.year, dt_utc.month, dt_utc.day,
                        dt_utc.hour + dt_utc.minute / 60 + dt_utc.second / 3600)
    jd_midnight = swe.julday(dt_utc.year, dt_utc.month, dt_utc.day, 0.0)
    sunrise, next_sunrise = _sunrise_window(jd_midnight, lat, lon)

    if jd_now < sunrise:
        # Still before today's sunrise -> belongs to yesterday's solar day.
        prev_midnight = jd_midnight - 1
        sunrise, next_sunrise = _sunrise_window(prev_midnight, lat, lon)
        weekday = (dt_utc - timedelta(days=1)).weekday()
    else:
        weekday = dt_utc.weekday()

    day_lord = WEEKDAY_LORD[weekday]
    hora_length = (next_sunrise - sunrise) / 24
    hora_number = max(0, int((jd_now - sunrise) / hora_length)) if hora_length > 0 else 0
    start_idx = CHALDEAN.index(day_lord)
    hora_lord = CHALDEAN[(start_idx + hora_number) % 7]
    return day_lord, hora_lord


def compute_chart(dt_utc: datetime, venue: str = "", country: str = "") -> dict:
    """Real sidereal chart for a UTC datetime + venue. Returns a dict of
    plain facts (signs, nakshatra, dignities, a simple momentum lean) meant
    to be handed to an LLM as GROUND TRUTH to narrate — the LLM should never
    be asked to invent planetary positions itself."""
    if dt_utc.tzinfo is not None:
        dt_utc = dt_utc.astimezone(timezone.utc).replace(tzinfo=None)
    lat, lon = venue_coords(venue, country)

    jd = swe.julday(dt_utc.year, dt_utc.month, dt_utc.day,
                    dt_utc.hour + dt_utc.minute / 60 + dt_utc.second / 3600)

    cusps, ascmc = swe.houses_ex(jd, lat, lon, b"W", flags=swe.FLG_SIDEREAL)
    asc_lon = ascmc[0] % 360
    ascendant_sign = _sign_of(asc_lon)
    seventh_house_sign = SIGNS[(SIGNS.index(ascendant_sign) + 6) % 12]

    moon_lon = _sidereal_longitude(jd, swe.MOON)
    moon_sign = _sign_of(moon_lon)
    moon_nakshatra = _nakshatra_of(moon_lon)
    sun_lon = _sidereal_longitude(jd, swe.SUN)
    moon_phase_deg = (moon_lon - sun_lon) % 360
    waxing = moon_phase_deg < 180
    moon_dignity = _dignity_label("Moon", moon_sign)
    moon_strength = (
        f"{'Waxing' if waxing else 'Waning'}, {moon_dignity}"
        if moon_dignity != "neutral" else f"{'Waxing' if waxing else 'Waning'}"
    )

    planets = {}
    for name in ("Mars", "Saturn", "Jupiter", "Rahu"):
        lon_ = _sidereal_longitude(jd, _PLANET_ID[name])
        sign = _sign_of(lon_)
        planets[name] = {"sign": sign, "degree": round(lon_ % 30, 1),
                         "dignity": _dignity_label(name, sign)}
    ketu_lon = (planets["Rahu"]["degree"] + SIGNS.index(planets["Rahu"]["sign"]) * 30 + 180) % 360
    ketu_sign = _sign_of(ketu_lon)
    planets["Ketu"] = {"sign": ketu_sign, "degree": round(ketu_lon % 30, 1),
                       "dignity": _dignity_label("Ketu", ketu_sign)}

    day_lord, hora_lord = _day_and_hora_lord(dt_utc, lat, lon)

    # Simple, explicitly-heuristic momentum lean: compare how many of
    # {ascendant sign lord placement quality, Moon dignity, benefic-in-1st}
    # favor the 1st house (home/team A by astrological convention) vs the
    # 7th (away/team B). This is intentionally coarse — framed to the LLM
    # as a "lean", never a certainty.
    home_score = (1 if moon_dignity in ("exalted", "in own sign") else 0)
    home_score += (1 if hora_lord in ("Jupiter", "Venus", "Sun") else 0)
    away_score = (1 if planets["Mars"]["dignity"] in ("exalted", "in own sign") else 0)
    away_score += (1 if hora_lord in ("Mars", "Saturn") else 0)
    if home_score > away_score:
        momentum_favors = "home/first-listed team"
    elif away_score > home_score:
        momentum_favors = "away/second-listed team"
    else:
        momentum_favors = "balanced — close contest indicated"

    return {
        "ascendant_sign": ascendant_sign,
        "seventh_house_sign": seventh_house_sign,
        "moon_sign": moon_sign,
        "moon_nakshatra": moon_nakshatra,
        "moon_strength": moon_strength,
        "day_lord": day_lord,
        "hora_lord": hora_lord,
        "planets": planets,   # Mars/Saturn/Jupiter/Rahu/Ketu -> sign/degree/dignity
        "momentum_favors": momentum_favors,
    }
