"""
channel_manager/community_poster.py — DriftWire326 Module 22
Posts a weekly watchlist community update every Sunday 09:00 AM ET.
Content is generated by Claude from the week's market data.

IMPORTANT: YouTube's activities.insert (Bulletin) endpoint was deprecated
in 2019. Channel community posts are now only accessible via YouTube Studio
UI or to YouTube Partner Program channels via special API access.
This module:
  1. Generates the post text via Claude (always works)
  2. Attempts the API post (works if channel has community post access)
  3. On API failure, saves the post to logs/community_posts/ for manual publishing
  4. Logs which path was taken so the operator knows
"""
import json
import logging
import os
from datetime import datetime, date
from pathlib import Path
from typing import Optional

import anthropic

from config.settings import settings
from monitor.usage_ledger import record

logger = logging.getLogger(__name__)

COMMUNITY_POSTS_DIR = settings.logs_dir / "community_posts"
COMMUNITY_POSTS_DIR.mkdir(parents=True, exist_ok=True)

# Hard character limit for YouTube community posts
POST_CHAR_LIMIT = 1200

# Fallback when market data files are unavailable
_FALLBACK_TICKERS = ["SPY", "QQQ", "AAPL", "NVDA", "MSFT", "TSLA", "JPM"]

_POST_GENERATION_PROMPT = """You are the voice of @DriftWire326, a YouTube finance channel for Gen Z and Millennial investors.

Write a weekly watchlist community post for this Sunday. Tone: confident, conversational, slightly informal — like a smart friend sharing their market perspective. NOT financial advice.

Week's market context:
{week_context}

Requirements:
- Max {char_limit} characters total
- Start with a hook (emoji optional)
- Include 4-6 specific tickers to watch next week with a brief one-line reason each
- End with "Drop your watchlist below 👇" or similar CTA
- Must include: "Not financial advice — do your own research."
- Do NOT mention guarantees, returns, or use any language that sounds like a recommendation to buy/sell

Return ONLY the post text, no preamble."""


def _get_youtube_service():
    from uploader.uploader import _get_authenticated_service
    return _get_authenticated_service()


def _get_claude_client() -> anthropic.Anthropic:
    return anthropic.Anthropic(api_key=settings.anthropic_api_key)


class CommunityPoster:
    """Generates and posts weekly watchlist community updates."""

    def __init__(self, youtube_service=None):
        self._svc = youtube_service

    def _service(self):
        if self._svc is None:
            self._svc = _get_youtube_service()
        return self._svc

    # ── Data gathering ───────────────────────────────────────────────────────

    def get_week_watchlist(self) -> dict:
        """
        Build week context from recent scraped market data files.
        Falls back to default watchlist tickers if no data available.
        """
        context: dict = {
            "week_ending": date.today().isoformat(),
            "top_movers": [],
            "indices": {},
            "macro_notes": "",
            "tickers": _FALLBACK_TICKERS,
        }

        # Try to load the most recent market data
        market_dir = settings.output_dir / "scripts"
        try:
            # Look for recent market JSON files (from market_scraper)
            data_files = sorted(
                (settings.output_dir / "scripts").glob("market_data_*.json"),
                reverse=True,
            )
            if data_files:
                data = json.loads(data_files[0].read_text())
                if "top_movers" in data:
                    context["top_movers"] = data["top_movers"][:5]
                if "indices" in data:
                    context["indices"] = data["indices"]
                if "macro" in data:
                    context["macro_notes"] = str(data["macro"])
                tickers = [m.get("ticker", "") for m in context["top_movers"] if m.get("ticker")]
                if tickers:
                    context["tickers"] = list(set(tickers + _FALLBACK_TICKERS))[:8]
        except Exception as exc:
            logger.warning("Could not load market data for community post: %s", exc)

        return context

    # ── Content generation ───────────────────────────────────────────────────

    def generate_post_text(self, week_data: dict) -> str:
        """
        Generate community post text via Claude.
        Always includes disclaimer. Hard-capped at POST_CHAR_LIMIT characters.
        """
        week_context_str = json.dumps(week_data, indent=2, default=str)
        prompt = _POST_GENERATION_PROMPT.format(
            week_context=week_context_str,
            char_limit=POST_CHAR_LIMIT,
        )

        try:
            client = _get_claude_client()
            message = client.messages.create(
                model=settings.claude_model,
                max_tokens=600,
                messages=[{"role": "user", "content": prompt}],
            )
            record(message, "community_poster")
            text = message.content[0].text.strip()
            # Hard cap
            if len(text) > POST_CHAR_LIMIT:
                text = text[: POST_CHAR_LIMIT - 3] + "..."
            logger.info("Community post generated (%d chars)", len(text))
            return text

        except Exception as exc:
            logger.error("Claude community post generation failed: %s", exc)
            # Minimal fallback post
            tickers = ", ".join(week_data.get("tickers", _FALLBACK_TICKERS)[:5])
            return (
                f"📊 Weekly Watchlist — {date.today().strftime('%B %d, %Y')}\n\n"
                f"Tickers on my radar this week: {tickers}\n\n"
                f"Drop your watchlist below 👇\n\n"
                f"Not financial advice — do your own research."
            )

    # ── Posting ──────────────────────────────────────────────────────────────

    def post_community_update(self, text: str) -> bool:
        """
        Attempt to post a community update via YouTube Data API v3.
        Note: Community post API access requires YouTube Partner Program.
        Falls back to saving the post text for manual publishing.
        Returns True if the post was published via API, False if saved for manual review.
        """
        api_success = self._try_api_post(text)
        if api_success:
            return True

        # Save for manual publishing
        self._save_for_manual_publish(text)
        return False

    def _try_api_post(self, text: str) -> bool:
        """
        Try posting via YouTube API activities.insert.
        This requires special access not available to all channels.
        """
        try:
            body = {
                "snippet": {
                    "description": text,
                },
                "contentDetails": {
                    "bulletin": {
                        "resourceId": {
                            "kind": "youtube#channel",
                            "channelId": settings.channel_id,
                        }
                    }
                },
            }
            self._service().activities().insert(
                part="snippet,contentDetails",
                body=body,
            ).execute()
            logger.info("Community post published via API (%d chars)", len(text))
            return True

        except Exception as exc:
            # 403 is expected for channels without Partner Program community post access
            logger.warning(
                "Community post API unavailable (expected for non-Partner channels): %s", exc
            )
            return False

    def _save_for_manual_publish(self, text: str) -> Path:
        """Save the generated post text to disk for manual publishing."""
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = COMMUNITY_POSTS_DIR / f"community_post_{ts}.txt"
        out_path.write_text(text, encoding="utf-8")
        logger.info(
            "Community post saved for manual publishing → %s\n"
            "Go to YouTube Studio → Community tab to publish.",
            out_path,
        )
        return out_path

    # ── Scheduled entrypoint ─────────────────────────────────────────────────

    def run_weekly_post(self) -> bool:
        """
        Main entrypoint called by SundayScheduler at 09:00 AM ET.
        Gathers week data → generates text → attempts post → logs result.
        Returns True if published via API, False if saved for manual review.
        """
        logger.info("Running weekly community post")
        week_data = self.get_week_watchlist()
        text = self.generate_post_text(week_data)
        published = self.post_community_update(text)

        # Always save a copy for the record
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        record_path = COMMUNITY_POSTS_DIR / f"record_{ts}.json"
        record_path.write_text(json.dumps({
            "generated_at": datetime.now().isoformat(),
            "week_data": week_data,
            "text": text,
            "char_count": len(text),
            "api_published": published,
        }, indent=2, default=str))

        if published:
            logger.info("Weekly community post published successfully")
        else:
            logger.info(
                "Weekly community post NOT auto-published (API unavailable). "
                "Saved to %s — publish manually via YouTube Studio → Community.",
                COMMUNITY_POSTS_DIR,
            )
        return published
